### ISSUE TITLE
Feature Request: Default handler for when codes don't have specific handlers

### ISSUE THREAD

**Issue by jmsgomes** [cncjs/gcode-interpreter#2]
As I understand it, currently only handlers specific for each command will be invoked when each G-Code line is interpreted. It would be useful if we could also provide a `defaultHandler` function (that accepts `cmd` and `args` as parameters) that would be called when a command does not have a specific handler.

For example,

```
const interpreter = new Interpreter(
  {
      handlers: { /** handlers for specific command */ }, 
      defaultHandler: (cmd, args) => {},  // Called when no handler is found for a command.
  }
);
```

**Comment by cheton** [comment]
Published v2.1.0

Thank you.
